# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RNUportSigner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNUportSigner
  pod 'UPTEthereumSigner', :git => 'https://github.com/uport-project/UPTEthereumSigner.git', :commit => '5afc51d93b24a778cbfc3bd69c44a91f3cb1f5c8'
  # pod 'CoreEthereum'

end
