# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RNUportSigner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RNUportSigner
  pod 'UPTEthereumSigner', :git => 'https://github.com/uport-project/UPTEthereumSigner'

end
